KAFKA-599 JMX long term support - update

diff --git a/bin/schema-registry-run-class b/bin/schema-registry-run-class
--- a/bin/schema-registry-run-class
+++ b/bin/schema-registry-run-class
@@ -189,43 +189,67 @@ if [ -z "$MAPR_JMXSSL" ]; then
   MAPR_JMXSSL="false"
 fi
 
+if [ -z "$MAPR_AUTH_LOGIN_CONFIG_FILE" ]; then
+  MAPR_AUTH_LOGIN_CONFIG_FILE="${MAPR_HOME:-/opt/mapr}/conf/mapr.login.conf"
+fi
+
+if [ -z "$MAPR_LOGIN_CONFIG" ]; then
+  MAPR_LOGIN_CONFIG="JMX_AGENT_LOGIN"
+fi
+
 if [ -z "$MAPR_JMXDISABLE" ] && [ -z "$MAPR_JMXLOCALHOST" ] && [ -z "$MAPR_JMXREMOTEHOST" ]; then
-  echo "WARNING: No MapR JMX options given - defaulting to local binding"
+  echo "No MapR JMX options given - defaulting to local binding"
 fi
 
 if [[ ( -z "$MAPR_JMXDISABLE" || "$MAPR_JMXDISABLE" = 'false' ) && \
-  ( -z "$MAPR_JMX_SCHEMA_REGISTRY_ENABLE" || "$MAPR_JMX_SCHEMA_REGISTRY_ENABLE" = "true" ) ]]; then
+      ( -z "$MAPR_JMX_SCHEMA_REGISTRY_ENABLE" || "$MAPR_JMX_SCHEMA_REGISTRY_ENABLE" = "true" ) ]]; then
+
   # default setting for localBinding
   MAPR_JMX_OPTS="-Dcom.sun.management.jmxremote"
-  if [ "$MAPR_JMXAUTH" = "true" ]; then
-    if [ "$isSecure" = "true" ]; then
-      if [ -f "${MAPR_HOME:-/opt/mapr}/conf/jmxremote.password" ] && [ -f "${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access" ]; then
-        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=true \
-        -Dcom.sun.management.jmxremote.password.file=${MAPR_HOME:-/opt/mapr}/conf/jmxremote.password \
-        -Dcom.sun.management.jmxremote.access.file=${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access"
-      else
-        echo "ERROR: JMX password and/or access files missing - not starting since we are in secure mode"
-        exit 1
-      fi
-    else
-      echo "ERROR: JMX Authentication configured - not starting since we are not in secure mode"
-      exit 1
-    fi
-  else
-    MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
-  fi
-  
+
   if [ "$MAPR_JMXLOCALHOST" = "true" ] && [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
     echo "WARNING: Both MAPR_JMXLOCALHOST and MAPR_JMXREMOTEHOST options are enabled - defaulting to MAPR_JMXLOCAHOST config"
     MAPR_JMXREMOTEHOST=false
   fi
 
-  if [ "$MAPR_JMXLOCALHOST" = "true" ] || [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
-    if [ "$MAPR_JMXSSL" = "true" ]; then
-      if [ "$MAPR_JMXLOCALHOST" = "true" ]; then
-        echo "WARNING: SSL not implemented with MAPR_JMXLOCALHOST"
-        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=false"
+  if [ "$isSecure" = "true" ] && [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
+    JMX_JAR=$(echo ${MAPR_HOME:-/opt/mapr}/lib/jmxagent*)
+    if [ -n "$JMX_JAR" ] && [ -f ${JMX_JAR} ]; then
+      MAPR_JMX_OPTS="-javaagent:$JMX_JAR \
+      -Dmapr.jmx.agent.login.config=$MAPR_LOGIN_CONFIG"
+      MAPR_JMXAUTH="true"
+    else
+      echo "jmxagent jar file missed"
+      exit 1
+    fi
+  fi
+
+  if [ "$MAPR_JMXAUTH" = "true" ]; then
+    if [ "$isSecure" = "true" ]; then
+      if [ -f "$MAPR_AUTH_LOGIN_CONFIG_FILE" ] && [ -f "${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access" ]; then
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=true \
+        -Djava.security.auth.login.config=$MAPR_AUTH_LOGIN_CONFIG_FILE \
+        -Dcom.sun.management.jmxremote.access.file=${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access"
+      else
+        echo "JMX login config or access file missing - not starting since we are in secure mode"
+        exit 1
       fi
+
+      if [ "$MAPR_JMXREMOTEHOST" = "false" ]; then
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.login.config=$MAPR_LOGIN_CONFIG"
+      fi
+    else
+      echo "JMX Authentication configured - not starting since we are not in secure mode"
+      exit 1
+    fi
+  else
+    MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
+  fi
+
+  if [ "$MAPR_JMXLOCALHOST" = "true" ] || [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
+    if [ "$MAPR_JMXSSL" = "true" ] && [ "$MAPR_JMXLOCALHOST" = "true" ] ; then
+      echo "WARNING: ssl is not supported in localhost. Setting default to false"
+      MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=false"
     else
       MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=false"
     fi
@@ -240,22 +264,20 @@ if [[ ( -z "$MAPR_JMXDISABLE" || "$MAPR_JMXDISABLE" = 'false' ) && \
       echo "WARNING: No JMX port given for Schema Registry - disabling TCP base JMX service"
       MAPR_JMX_OPTS=""
     else
-      if [ "$MAPR_JMXLOCALHOST" = "true" ]; then
-        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.port=$MAPR_JMX_PORT"
-        echo "Enabling TCP JMX for Schema Registry only on localhost port $MAPR_JMX_PORT"
-      else
+      if [ "$MAPR_JMXREMOTEHOST" = "true" ] && [ "$isSecure" = "true" ]; then
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dmapr.jmx.agent.port=$MAPR_JMX_PORT"
         echo "Enabling TCP JMX for Schema Registry on port $MAPR_JMX_PORT"
-        JMX_JAR=$(echo ${MAPR_HOME:-/opt/mapr}/lib/jmxagent*)
-        if [ -f $JMX_JAR ]; then
-          MAPR_JMX_OPTS="-javaagent:$JMX_JAR -Dmapr.jmx.agent.login.config=JMX_AGENT_LOGIN -Dmapr.jmx.agent.port=$MAPR_JMX_PORT"
+      else
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.port=$MAPR_JMX_PORT"
+        if [ "$MAPR_JMXLOCALHOST" = "true" ]; then
+          echo "Enabling TCP JMX for Schema Registry only on localhost port $MAPR_JMX_PORT"
         else
-          echo "Failed to find jmxagent jar - starting without remote JMX service"
-          MAPR_JMX_OPTS=""
+          echo "Enabling TCP JMX for Schema Registry on port $MAPR_JMX_PORT"
         fi
       fi
     fi
-  fi      
-        
+  fi
+    
   if [ "$MAPR_JMXLOCALBINDING" = "true" ] && [ -z "$MAPR_JMX_OPTS" ]; then
     echo "Enabling JMX local binding only"
     MAPR_JMX_OPTS="-Dcom.sun.management.jmxremote"
@@ -266,8 +288,6 @@ else
 fi
 
 SCHEMA_REGISTRY_JMX_OPTS=$MAPR_JMX_OPTS
-echo "JMX options:"
-echo $SCHEMA_REGISTRY_JMX_OPTS
 
 # Launch mode
 if [ "x$DAEMON_MODE" = "xtrue" ]; then
