KAFKA-1014 Port EEP specific changes to schema-registry 7.6.0
This commit brings squashed combination of EEP-specific commits from  https://github.com/mapr/private-schema-registry/commit/3f9e8248595772924f96729fff79232e743f3a71 to https://github.com/mapr/private-schema-registry/commit/29df9edf3dac1fc81b1df4375c931703488fbc33i

diff --git a/bin/schema-registry-run-class b/bin/schema-registry-run-class
--- a/bin/schema-registry-run-class
+++ b/bin/schema-registry-run-class
@@ -15,6 +15,10 @@
 # limitations under the License.
 #
 
+# calling env var and its overridden file
+env=${MAPR_HOME:-/opt/mapr}/conf/env.sh
+[ -f $env ] && . $env
+
 if [ $# -lt 1 ];
 then
   echo "USAGE: $0 [-daemon] [-name servicename] [-loggc] classname [opts]"
@@ -30,6 +34,9 @@ else
   CYGWIN=0
 fi
 
+# This will set MAPR_HOME, etc.
+source `which mapr-config.sh` # Both "mapr" and "mapr-config.sh" are symlinked in "/usr/bin"
+
 # Development jars. `mvn package` should collect all the required dependency jars here
 for dir in $base_dir/package-schema-registry/target/kafka-schema-registry-package-*-development; do
   CLASSPATH=$CLASSPATH:$dir/share/java/schema-registry/*
@@ -39,6 +46,10 @@ done
 for library in "confluent-security/schema-registry" "schema-registry-plugins" "confluent-common" "confluent-telemetry" "rest-utils" "schema-registry"; do
   CLASSPATH=$CLASSPATH:$base_dir/share/java/$library/*      
 done
+
+# Add logger jars
+CLASSPATH=$CLASSPATH:$(get_log4j12_jars) # function in mapr-config.sh
+CLASSPATH=$CLASSPATH:$(get_mapr_app_jars) # function in mapr-config.sh
 
 # Log directory to use
 if [ "x$LOG_DIR" = "x" ]; then
@@ -72,16 +83,6 @@ fi
 (( CYGWIN )) && LOG_DIR=$(cygpath --path --mixed "${LOG_DIR}")
 
 SCHEMA_REGISTRY_LOG4J_OPTS="-Dschema-registry.log.dir=$LOG_DIR $SCHEMA_REGISTRY_LOG4J_OPTS"
-
-# JMX settings
-if [ -z "$SCHEMA_REGISTRY_JMX_OPTS" ]; then
-  SCHEMA_REGISTRY_JMX_OPTS="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false "
-fi
-
-# JMX port to use
-if [  $JMX_PORT ]; then
-  SCHEMA_REGISTRY_JMX_OPTS="$SCHEMA_REGISTRY_JMX_OPTS -Dcom.sun.management.jmxremote.port=$JMX_PORT "
-fi
 
 # Generic jvm settings you want to add
 if [ -z "$SCHEMA_REGISTRY_OPTS" ]; then
@@ -166,10 +167,170 @@ fi
 # If Cygwin is detected, classpath is converted to Windows format.
 (( CYGWIN )) && CLASSPATH=$(cygpath --path --mixed "${CLASSPATH}")
 
+PID="/dev/null" # SKIP PID file for AVRO Producer / Consumer
+if [[ $MAIN == *"SchemaRegistryMain" ]]; then
+    PID="${BASEMAPR:-/opt/mapr}/pid/schemaregistry.pid"
+fi
+
+MAPR_CLIENT_CLASSPATH=$(mapr clientclasspath)
+KAFKA_EVENTSTREAMS_CLASSPATH=$(find ${BASEMAPR:-/opt/mapr}/kafka -name "kafka-eventstreams-*.jar")
+MAPR_CLIENT_CLASSPATH=$MAPR_CLIENT_CLASSPATH:$KAFKA_EVENTSTREAMS_CLASSPATH
+# Add mapr-security-web.jar
+for file in "${BASEMAPR:-/opt/mapr}"/lib/mapr-security-web-*.jar
+do
+  MAPR_CLIENT_CLASSPATH="$MAPR_CLIENT_CLASSPATH":"$file"
+done
+#Add fips jars
+for file in $(find ${BASEMAPR:-/opt/mapr}/kafka -name "*-fips-*.jar")
+do
+  MAPR_CLIENT_CLASSPATH="$MAPR_CLIENT_CLASSPATH":"$file"
+done
+SCHEMA_REGISTRY_CLASSPATH=$CLASSPATH:$MAPR_CLIENT_CLASSPATH
+
+# To enable PAM:
+JAVA_LIB_PATH="-Djava.library.path=${BASEMAPR:-/opt/mapr}/lib/"
+SCHEMA_REGISTRY_CLASSPATH=$SCHEMA_REGISTRY_CLASSPATH:${BASEMAPR:-/opt/mapr}/lib/JPam-1.1.jar
+
+echo $$ > $PID
+
+# JMX Agent options:
+isSecure="false"
+if [ -f "${MAPR_HOME:-/opt/mapr}/conf/mapr-clusters.conf" ]; then
+  isSecure=$(head -1 ${MAPR_HOME:-/opt/mapr}/conf/mapr-clusters.conf | grep -o 'secure=\w*' | cut -d= -f2)
+fi
+
+MAPR_JMX_PORT=${MAPR_JMX_SCHEMA_REGISTRY_PORT:-3414}
+
+JMX_JAR=$(echo ${MAPR_HOME:-/opt/mapr}/lib/jmxagent*)
+
+if [ -z "$MAPR_JMXLOCALBINDING" ]; then
+  MAPR_JMXLOCALBINDING="false"
+fi
+
+if [ -z "$MAPR_JMXAUTH" ]; then
+  MAPR_JMXAUTH="false"
+fi
+
+if [ -z "$MAPR_JMXSSL" ]; then
+  MAPR_JMXSSL="false"
+fi
+
+if [ -z "$MAPR_AUTH_LOGIN_CONFIG_FILE" ]; then
+  MAPR_AUTH_LOGIN_CONFIG_FILE="${MAPR_HOME:-/opt/mapr}/conf/mapr.login.conf"
+fi
+
+if [ -z "$MAPR_LOGIN_CONFIG" ]; then
+  MAPR_LOGIN_CONFIG="JMX_AGENT_LOGIN"
+fi
+
+if [ -z "$MAPR_JMXDISABLE" ] && [ -z "$MAPR_JMXLOCALHOST" ] && [ -z "$MAPR_JMXREMOTEHOST" ]; then
+  echo "No MapR JMX options given - defaulting to local binding"
+fi
+
+if [[ ( -z "$MAPR_JMXDISABLE" || "$MAPR_JMXDISABLE" = 'false' ) && ( $MAIN == *"SchemaRegistryMain" ) && \
+      ( -z "$MAPR_JMX_SCHEMA_REGISTRY_ENABLE" || "$MAPR_JMX_SCHEMA_REGISTRY_ENABLE" = "true" ) ]]; then
+
+  # default setting for localBinding
+  MAPR_JMX_OPTS="-Dcom.sun.management.jmxremote"
+
+  if [ "$MAPR_JMXLOCALHOST" = "true" ] && [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
+    echo "WARNING: Both MAPR_JMXLOCALHOST and MAPR_JMXREMOTEHOST options are enabled - defaulting to MAPR_JMXLOCAHOST config"
+    MAPR_JMXREMOTEHOST=false
+  fi
+
+  if [ "$isSecure" = "true" ] && [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
+    if [ -n "$JMX_JAR" ] && [ -f ${JMX_JAR} ]; then
+      MAPR_JMX_OPTS="-javaagent:$JMX_JAR \
+      -Dmapr.jmx.agent.login.config=$MAPR_LOGIN_CONFIG"
+      MAPR_JMXAUTH="true"
+    else
+      echo "jmxagent jar file missed"
+      exit 1
+    fi
+  fi
+
+  if [ "$MAPR_JMXAUTH" = "true" ]; then
+    if [ "$isSecure" = "true" ]; then
+      if [ -f "$MAPR_AUTH_LOGIN_CONFIG_FILE" ] && [ -f "${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access" ]; then
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=true \
+        -Djava.security.auth.login.config=$MAPR_AUTH_LOGIN_CONFIG_FILE \
+        -Dcom.sun.management.jmxremote.access.file=${MAPR_HOME:-/opt/mapr}/conf/jmxremote.access"
+      else
+        echo "JMX login config or access file missing - not starting since we are in secure mode"
+        exit 1
+      fi
+
+      if [ "$MAPR_JMXREMOTEHOST" = "false" ]; then
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.login.config=$MAPR_LOGIN_CONFIG"
+      fi
+    else
+      echo "JMX Authentication configured - not starting since we are not in secure mode"
+      exit 1
+    fi
+  else
+    MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.authenticate=false"
+  fi
+
+  if [ "$MAPR_JMXLOCALHOST" = "true" ] || [ "$MAPR_JMXREMOTEHOST" = "true" ]; then
+    if [ "$MAPR_JMXSSL" = "true" ] && [ "$MAPR_JMXLOCALHOST" = "true" ] ; then
+      echo "WARNING: ssl is not supported in localhost. Setting default to false"
+      MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=false"
+    else
+      MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.ssl=false"
+    fi
+
+    if [ "$MAPR_JMXLOCALHOST" = "true" ]; then
+      MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Djava.rmi.server.hostname=localhost \
+      -Dcom.sun.management.jmxremote.host=localhost \
+      -Dcom.sun.management.jmxremote.local.only=true"
+    fi
+
+    if [ -z "$MAPR_JMX_PORT" ]; then
+      echo "WARNING: No JMX port given for Schema Registry - disabling TCP base JMX service"
+      MAPR_JMX_OPTS=""
+    else
+      if [ "$MAPR_JMXREMOTEHOST" = "true" ] && [ "$isSecure" = "true" ]; then
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dmapr.jmx.agent.port=$MAPR_JMX_PORT"
+        echo "Enabling TCP JMX for Schema Registry on port $MAPR_JMX_PORT"
+      else
+        MAPR_JMX_OPTS="$MAPR_JMX_OPTS -Dcom.sun.management.jmxremote.port=$MAPR_JMX_PORT"
+        if [ "$MAPR_JMXLOCALHOST" = "true" ]; then
+          echo "Enabling TCP JMX for Schema Registry only on localhost port $MAPR_JMX_PORT"
+        else
+          echo "Enabling TCP JMX for Schema Registry on port $MAPR_JMX_PORT"
+        fi
+      fi
+    fi
+  fi
+
+  if [ "$MAPR_JMXLOCALBINDING" = "true" ] && [ -z "$MAPR_JMX_OPTS" ]; then
+    echo "Enabling JMX local binding only"
+    MAPR_JMX_OPTS="-Dcom.sun.management.jmxremote"
+  fi
+else
+  if [[ $MAIN != *"SchemaRegistryMain" ]]; then
+    echo "JMX disabled - It is used for only Schema Registry server (skipped for avro consumer and producer)."
+  else
+    echo "JMX disabled by user request"
+  fi
+  MAPR_JMX_OPTS=""
+fi
+
+SCHEMA_REGISTRY_JMX_OPTS=$MAPR_JMX_OPTS
+
+if [ -f ${JMX_JAR} ]; then
+  SCHEMA_REGISTRY_CLASSPATH=$SCHEMA_REGISTRY_CLASSPATH:$JMX_JAR
+fi
+
+# if FIPS mode is enabled, add security java options
+env=${MAPR_HOME:-/opt/mapr}/conf/env.sh
+[ -f "${env}" ] && . "${env}"
+SCHEMA_REGISTRY_OPTS="${SCHEMA_REGISTRY_OPTS} ${MAPR_COMMON_JAVA_OPTS}"
+
 # Launch mode
 if [ "x$DAEMON_MODE" = "xtrue" ]; then
   CONSOLE_OUTPUT_FILE=${CONSOLE_OUTPUT_FILE:-${LOG_DIR}/schema-registry-console.out}
-  nohup $JAVA $SCHEMA_REGISTRY_HEAP_OPTS $SCHEMA_REGISTRY_JVM_PERFORMANCE_OPTS $SCHEMA_REGISTRY_GC_LOG_OPTS $SCHEMA_REGISTRY_JMX_OPTS $SCHEMA_REGISTRY_LOG4J_OPTS -cp $CLASSPATH $SCHEMA_REGISTRY_OPTS "$MAIN" "$@" > "${CONSOLE_OUTPUT_FILE}" 2>&1 < /dev/null &
+  nohup $JAVA $JAVA_LIB_PATH $SCHEMA_REGISTRY_HEAP_OPTS $SCHEMA_REGISTRY_JVM_PERFORMANCE_OPTS $SCHEMA_REGISTRY_GC_LOG_OPTS $SCHEMA_REGISTRY_JMX_OPTS $SCHEMA_REGISTRY_LOG4J_OPTS -cp $SCHEMA_REGISTRY_CLASSPATH $SCHEMA_REGISTRY_OPTS "$MAIN" "$@" > "${CONSOLE_OUTPUT_FILE}" 2>&1 < /dev/null
 else
-  exec "$JAVA" $SCHEMA_REGISTRY_HEAP_OPTS $SCHEMA_REGISTRY_JVM_PERFORMANCE_OPTS $SCHEMA_REGISTRY_GC_LOG_OPTS $SCHEMA_REGISTRY_JMX_OPTS $SCHEMA_REGISTRY_LOG4J_OPTS -cp $CLASSPATH $SCHEMA_REGISTRY_OPTS "$MAIN" "$@"
+  exec "$JAVA" $JAVA_LIB_PATH $SCHEMA_REGISTRY_HEAP_OPTS $SCHEMA_REGISTRY_JVM_PERFORMANCE_OPTS $SCHEMA_REGISTRY_GC_LOG_OPTS $SCHEMA_REGISTRY_JMX_OPTS $SCHEMA_REGISTRY_LOG4J_OPTS -cp $SCHEMA_REGISTRY_CLASSPATH $SCHEMA_REGISTRY_OPTS "$MAIN" "$@"
 fi
